<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Main_T1ms" Id="{f7339b70-7acd-4fbe-83cc-3fa441c021ee}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Main_T1ms
VAR
			 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// time stamp generation
TimeStamp(); 


]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>